/** User Types * */
export const USER_SET_HERO = 'USER_SET_HERO';
export const USER_SET_USERNAME = 'USER_SET_USERNAME';

/** Card Types * */
export const FETCH_CARDS_INITIATE = 'FETCH_CARDS_INITIATE';
export const FETCH_CARDS_COMPLETE = 'FETCH_CARDS_COMPLETE';
export const FETCH_CARDS_ERROR = 'FETCH_CARDS_ERROR';
